FROM node:14-alpine AS build
WORKDIR /app

ARG VITE_WEBSOCKET_URL
ENV VITE_WEBSOCKET_URL=${VITE_WEBSOCKET_URL}

WORKDIR /app/ui
COPY --chown=node:node ui/ ./
RUN yarn install --production=false
RUN npm install -g typescript@4.3.4
RUN yarn build:ts
RUN yarn build:vite

FROM nginx:1.17.1-alpine
COPY --from=build /app/ui/dist/ /usr/share/nginx/html
COPY --from=build /app/ui/nginx.conf /etc/nginx/conf.d/default.conf

