FROM node:14-alpine AS build
WORKDIR /app

ARG VITE_REGISTRY_URL
ENV VITE_REGISTRY_URL=${VITE_REGISTRY_URL}}

COPY package.json .

RUN yarn install --production=false
COPY --chown=node:node . .
RUN npm install -g typescript@4.3.4
RUN yarn build:ts
RUN yarn build:vite

FROM nginx:1.17.1-alpine
COPY --from=build /app/dist/ /usr/share/nginx/html
COPY --from=build /app/nginx.conf /etc/nginx/conf.d/default.conf

